{% if environ.get('TRAVIS', False) %}
  {% set version = environ.get('TRAVIS_BRANCH', '0.0') %}
  {% set build_num = environ['TRAVIS_BUILD_NUMBER'] %}
{% elif environ.get('APPVEYOR', False) %}
  {% set version = environ.get('APPVEYOR_REPO_TAG_NAME', '0.0') %}
  {% set build_num = environ['APPVEYOR_BUILD_NUMBER'] %}
{% else %}
  {% set version = environ.get('GIT_DESCRIBE_TAG', '0.0') %}
  {% set build_num = environ.get('GIT_DESCRIBE_NUMBER', 0) %}
{% endif %}
{% set version = version.replace('v','').replace('untagged', '0.0').split('-')[0] %}

package:
  name: pydrobert-pytorch
  version: {{ version }}

source:
  path: ..

requirements:
  build:
    - python >=3.6
    - setuptools
    - setuptools_scm
  run:
    - python >=3.6
    - pytorch >=1.0.1
    - param
  run_constrained:
    - pydrobert-param >0.2.0
    - pydrobert-kaldi >0.5.3
    - pydrobert-speech >0.1.0

build:
  noarch: python
  skip: True  # [py < 36 or py == 39]
  number: {{ build_num }}
  entry_points:
    - compute-torch-token-data-dir-error-rates = pydrobert.torch.command_line:compute_torch_token_data_dir_error_rates
    - ctm-to-torch-token-data-dir = pydrobert.torch.command_line:ctm_to_torch_token_data_dir
    - get-torch-spect-data-dir-info = pydrobert.torch.command_line:get_torch_spect_data_dir_info
    - torch-token-data-dir-to-ctm = pydrobert.torch.command_line:torch_token_data_dir_to_ctm
    - torch-token-data-dir-to-trn = pydrobert.torch.command_line:torch_token_data_dir_to_trn
    - trn-to-torch-token-data-dir = pydrobert.torch.command_line:trn_to_torch_token_data_dir
  script:
    - export SETUPTOOLS_SCM_PRETEND_VERSION=${PKG_VERSION}  # [not win]
    - set SETUPTOOLS_SCM_PRETEND_VERSION=%PKG_VERSION%  # [win]
    - python setup.py install --single-version-externally-managed --record=record.txt

test:
  source_files:
    - tests
    - pytest.ini
  requires:
    - pytest
    - cudatoolkit
  imports:
    - pydrobert
    - pydrobert.torch
    - pydrobert.torch.command_line
    - pydrobert.torch.data
    - pydrobert.torch.estimators
    - pydrobert.torch.layers
    - pydrobert.torch.training
    - pydrobert.torch.util
  commands:
    - compute-torch-token-data-dir-error-rates --help
    - ctm-to-torch-token-data-dir --help
    - get-torch-spect-data-dir-info --help
    - torch-token-data-dir-to-ctm --help
    - torch-token-data-dir-to-trn --help
    - trn-to-torch-token-data-dir --help
    - pytest -x

about:
  home: https://github.com/sdrobert/pydrobert-pytorch
  license: Apache License 2.0
  license_family: APACHE
  license_file: LICENSE
  summary: PyTorch utilities for ML, specifically speech
