version: build.{build}.branch.{branch}
image: Visual Studio 2019

environment:
  matrix:
    - TOXENV: py36-earliest
    - TOXENV: py37
    - TOXENV: py38
    - TOXENV: py39
    # - TOXENV: py310  # wheel not available yet

build: off

for:
  -
    matrix:
      only:
        - TOXENV: /py37/
    skip_non_tags: true

init:
  - cmd: set PATH=C:\Python37-x64;C:\Python37-x64\Scripts;%PATH%

install:
  - python -m pip install -U virtualenv setuptools wheel six
  - python -m pip install -U tox tox-ltt

test_script:
  - python -m tox

branches:
  except:
    - /docs/