version: build.{build}.branch.{branch}
# FIXME(sdrobert): tox-ltt doesn't work on Windows as of yet, causing a
# virtualenv error. Until it's fixed we'll use the Ubuntu image.
image: Ubuntu

environment:
  matrix:
    - TOXENV: py37-t151
      PYTHON: "3.7"
      NO_SCRIPT: "1"
    - TOXENV: py38-t181
      PYTHON: "3.8"
      ONLY_SCRIPT: "1"
    - TOXENV: py39
      PYTHON: "3.9"
    # - TOXENV: py310
    #   PYTHON: "3.10"

stack: python %PYTHON%

branches:
  except:
    - /docs/

for:
  -
    matrix:
      only:
        - PYTHON: "3.8"
        # - PYTHON: "3.9"
    skip_non_tags: true

build: off

install:
  - python3 -m pip install -U pip virtualenv setuptools wheel six
  # FIXME(sdrobert): https://github.com/pmeier/tox-ltt/issues/17
  - python3 -m pip install -U tox tox-ltt "light-the-torch<0.4.0"

test_script:
  - >-
    if [ ! -z "$NO_SCRIPT" ]; then
      export PYTORCH_JIT=0
      PYTEST_ARGS=( '-m' 'not trace and not script' )
    elif [ ! -z "$ONLY_SCRIPT" ]; then
      PYTEST_ARGS=( '-m' 'script or trace' )
    fi
  - python3 -m tox -- "${PYTEST_ARGS[@]}"
