version: build.{build}.branch.{branch}
image: Ubuntu

environment:
  matrix:
    - TOXENV: py36-earliest
    - TOXENV: py37
    - TOXENV: py38
    - TOXENV: py39
    # - TOXENV: py310  # wheel not available yet

branches:
  except:
    - /docs/

for:
  -
    matrix:
      only:
        - TOXENV: /py37/
    skip_non_tags: true

build: off

install:
  - python3.7 -m pip install -U pip virtualenv setuptools wheel six
  - python3.7 -m pip install -U tox tox-ltt

test_script:
  - python3.7 -m tox
