version: build.{build}.branch.{branch}
image: Ubuntu

environment:
  matrix:
    - TOXENV: py36-earliest
    - TOXENV: py37
    - TOXENV: py38
    - TOXENV: py39
    # - TOXENV: py310  # wheel not available yet

build: off

stack: python 3.7

for:
  -
    matrix:
      only:
        - TOXENV: /py37/
    skip_non_tags: true

install:
  - python -m pip install -U pip virtualenv setuptools wheel six
  - python -m pip install -U tox tox-ltt tox-appveyor

test_script:
  - python -m tox

branches:
  except:
    - /docs/