version: build.{build}.branch.{branch}
image: Visual Studio 2019

environment:
  matrix:
    - TOXENV: py36-earliest
    - TOXENV: py37
    - TOXENV: py38
    - TOXENV: py39
    # - TOXENV: py310  # wheel not available yet

build: off

for:
  -
    matrix:
      only:
        - TOXENV: /py3[7-8]/
    skip_non_tags: true

install:
  - C:\Python37-x64\python -m pip install tox tox-ltt

test_script:
  - C:\Python37-x64\python -m tox

branches:
  except:
    - /docs/