# Micromamba environment file
# https://marketplace.visualstudio.com/items?itemName=corker.vscode-micromamba

name: default

channels:
  - sdrobert
  - pytorch
  - conda-forge

dependencies:
  - pytorch
  - python
  - pytorch-lightning>=1.7
  - pydrobert-param>=0.4.0
  - pytest
  - webdataset
  - pydrobert-speech>=0.2.0
